wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.33
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    m:
    - 1: trainer/global_step
      6:
      - 3
    - 1: train_loss_step
      5: 1
      6:
      - 1
    - 1: epoch
      5: 1
      6:
      - 1
    - 1: train_loss_epoch
      5: 1
      6:
      - 1
    - 1: gradients/l1\.bias._type
      5: 1
      6:
      - 1
    - 1: gradients/l1\.bias.values
      5: 1
      6:
      - 1
    - 1: gradients/l1\.bias.bins
      5: 1
      6:
      - 1
    - 1: gradients/l1\.weight._type
      5: 1
      6:
      - 1
    - 1: gradients/l1\.weight.values
      5: 1
      6:
      - 1
    - 1: gradients/l1\.weight.bins
      5: 1
      6:
      - 1
    - 1: validation_loss
      5: 1
      6:
      - 1
    - 1: test_loss
      5: 1
      6:
      - 1
    python_version: 3.8.8
    t:
      1:
      - 1
      - 5
      - 9
      2:
      - 1
      - 5
      - 9
      3:
      - 1
      - 7
      4: 3.8.8
      5: 0.10.33
      8:
      - 5
batch_size:
  desc: null
  value: 8
epochs:
  desc: null
  value: 200
eps:
  desc: null
  value: 1.0e-08
img_size:
  desc: null
  value: 256
lr:
  desc: null
  value: 0.0004
mode:
  desc: null
  value: basic-mlp
num_classes:
  desc: null
  value: 4
total_steps:
  desc: null
  value: 211000
